version: '3.8'

services:
  notification-service:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: notification-service
    restart: always
    ports:
      - "8004:8004"
    environment:
      - POSTGRES_SERVER=postgres
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
      - POSTGRES_DB=notification_service
      - POSTGRES_PORT=5432
      - DEBUG=true
      - BACKEND_CORS_ORIGINS=["http://localhost:3000", "http://localhost:8000"]
      - SMTP_HOST=mailhog
      - SMTP_PORT=1025
      - SMTP_USER=
      - SMTP_PASSWORD=
      - EMAIL_FROM=noreply@example.com
      - EMAIL_FROM_NAME=New Data Collector
      - RABBITMQ_HOST=rabbitmq
      - RABBITMQ_PORT=5672
      - RABBITMQ_USER=guest
      - RABBITMQ_PASSWORD=guest
      - REDIS_HOST=redis
      - REDIS_PORT=6379
    volumes:
      - ./:/app
    depends_on:
      - postgres
      - rabbitmq
      - redis
      - mailhog
    networks:
      - data-collector-network

  postgres:
    image: postgres:15
    container_name: notification-postgres
    restart: always
    ports:
      - "5434:5432"
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
      - POSTGRES_DB=notification_service
    volumes:
      - postgres_data:/var/lib/postgresql/data
    networks:
      - data-collector-network

  rabbitmq:
    image: rabbitmq:3-management
    container_name: notification-rabbitmq
    restart: always
    ports:
      - "5674:5672"
      - "15674:15672"
    environment:
      - RABBITMQ_DEFAULT_USER=guest
      - RABBITMQ_DEFAULT_PASS=guest
    volumes:
      - rabbitmq_data:/var/lib/rabbitmq
    networks:
      - data-collector-network

  redis:
    image: redis:7
    container_name: notification-redis
    restart: always
    ports:
      - "6379:6379"
    volumes:
      - redis_data:/data
    networks:
      - data-collector-network

  mailhog:
    image: mailhog/mailhog
    container_name: notification-mailhog
    restart: always
    ports:
      - "1025:1025"  # SMTP 서버
      - "8025:8025"  # 웹 UI
    networks:
      - data-collector-network

volumes:
  postgres_data:
  rabbitmq_data:
  redis_data:

networks:
  data-collector-network:
    driver: bridge 